"""Two-stage bindings cache: key completeness + stage-1 hit validation
(audit W05, 2026-09-22) and manifest lost-update (W06).

CPU-only: ``generate_sources`` / ``compile_sources`` are replaced by stubs that
write the files the store expects, so every case runs without nvcc or a GPU.
The stubs COUNT their calls — that is the whole assertion surface:

    stage-1 hit   -> neither called
    stage-1 miss, identical bytes -> generate called, compile NOT called
    stage-1 miss, new bytes       -> both called
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import threading
from pathlib import Path

import pytest

import grim
from grim import _cache

URDF = "<robot name='cache_probe'><link name='base'/></robot>"
ARCH = 120


class _Stubs:
    """Fake generation/compile halves with call counters + a knob to change
    the generated bytes (simulating a codegen edit that changes emission)."""

    def __init__(self):
        self.generate_calls = 0
        self.compile_calls = 0
        self.emitted = "// grim.cuh v1\n"

    def generate_sources(self, urdf_path, options, out_dir):
        self.generate_calls += 1
        out_dir = Path(out_dir)
        (out_dir / "grim.cuh").write_text(self.emitted)
        (out_dir / "wrapper.cu").write_text("// wrapper\n")
        return {"NUM_JOINTS": 1, "NUM_VEL": 1, "NUM_EES": 0}

    def compile_sources(self, gen_dir, meta, options, *, cuda_arch, max_batch,
                        torch_op_key):
        self.compile_calls += 1
        gen_dir = Path(gen_dir)
        (gen_dir / "robot.so").write_bytes(b"\x7fELF-stub")
        meta = dict(meta, cuda_arch=cuda_arch, max_batch=max_batch)
        (gen_dir / "meta.json").write_text(json.dumps(meta))
        return meta


@pytest.fixture
def stubs(monkeypatch, tmp_path):
    st = _Stubs()
    monkeypatch.setattr(grim, "generate_sources", st.generate_sources)
    monkeypatch.setattr(grim, "compile_sources", st.compile_sources)
    # Keep the launch-config lookup from touching the real config tree.
    monkeypatch.setattr(grim, "_warn_if_no_ffi_autotune", lambda *a, **k: None)
    st.cache_dir = tmp_path / "cache"
    return st


def _warm(st, name="probe", **kw):
    return grim.warm_robot(name, urdf_string=URDF, cache_dir=st.cache_dir,
                               cuda_arch=ARCH, **kw)


def _bykey_entries(cache_dir):
    return sorted(p.name for p in (cache_dir / "bykey").iterdir()
                  if not p.name.startswith("."))


# ─── the three reuse regimes ────────────────────────────────────────────────

def test_cold_then_warm_hit_skips_both_halves(stubs):
    key, so, meta = _warm(stubs)
    assert (stubs.generate_calls, stubs.compile_calls) == (1, 1)
    assert so.exists() and (so.parent / _cache.BUILD_INPUTS_FILE).exists()
    key2, so2, _ = _warm(stubs)
    assert (key2, so2) == (key, so)
    assert (stubs.generate_calls, stubs.compile_calls) == (1, 1)


def test_codegen_edit_with_identical_bytes_skips_nvcc(stubs, monkeypatch):
    key, so, _ = _warm(stubs)
    # A codegen-tree edit rotates the stage-1 key (source-tree hash) but the
    # emitted bytes are unchanged -> generation-only reuse of the same entry.
    monkeypatch.setattr(_cache, "_codegen_source_hash", lambda: "edited-tree")
    key2, so2, _ = _warm(stubs)
    assert (key2, so2) == (key, so)
    assert (stubs.generate_calls, stubs.compile_calls) == (2, 1)


def test_emission_change_rebuilds(stubs, monkeypatch):
    key, so, _ = _warm(stubs)
    monkeypatch.setattr(_cache, "_codegen_source_hash", lambda: "edited-tree")
    stubs.emitted = "// grim.cuh v2\n"
    key2, so2, _ = _warm(stubs)
    assert key2 != key and so2 != so
    assert (stubs.generate_calls, stubs.compile_calls) == (2, 2)


# ─── W05: every identity input rotates the stage-1 key ──────────────────────

IDENTITY_KNOBS = [
    ("nvcc", lambda mp: mp.setattr(_cache, "_nvcc_identity", lambda: "/other/nvcc:99.0")),
    ("host_cxx", lambda mp: mp.setattr(_cache, "_host_cxx_tag", lambda: "/other/c++:1.0")),
    ("glass_content", lambda mp: mp.setattr(_cache, "_glass_content_hash", lambda: "dirty" * 8)),
    ("compile_py", lambda mp: mp.setattr(_cache, "_compile_source_hash", lambda: "edited")),
    ("wrapper_template", lambda mp: mp.setattr(_cache, "_wrapper_template_hash", lambda: "edited")),
    ("torch_abi", lambda mp: mp.setattr(_cache, "_torch_abi_tag", lambda: "torch=0.0,cxxabi=0")),
    ("jax_ffi", lambda mp: mp.setattr(_cache, "_jax_ffi_tag", lambda: "jaxffi=0.0")),
    ("env:GRIM_CUDA_TARGET_SHARED_MEM_BYTES",
     lambda mp: mp.setenv("GRIM_CUDA_TARGET_SHARED_MEM_BYTES", "65536")),
    ("env:GRIM_CUDA_TARGET_LITE_SHARED_MEM_BYTES",
     lambda mp: mp.setenv("GRIM_CUDA_TARGET_LITE_SHARED_MEM_BYTES", "32768")),
    ("env:GRIM_CUDA_SHARED_MEM_TYPE_SIZE_BYTES",
     lambda mp: mp.setenv("GRIM_CUDA_SHARED_MEM_TYPE_SIZE_BYTES", "8")),
    ("env:GRIM_NO_LICM_BARRIER", lambda mp: mp.setenv("GRIM_NO_LICM_BARRIER", "1")),
]


@pytest.fixture(autouse=True)
def _clean_generation_env(monkeypatch):
    for k in _cache.GENERATION_ENV_KNOBS:
        monkeypatch.delenv(k, raising=False)


@pytest.mark.parametrize("label,mutate", IDENTITY_KNOBS, ids=[k for k, _ in IDENTITY_KNOBS])
def test_identity_input_rotates_stage1_key(stubs, monkeypatch, label, mutate):
    key, so, _ = _warm(stubs)
    before = _bykey_entries(stubs.cache_dir)
    mutate(monkeypatch)
    _warm(stubs)
    after = _bykey_entries(stubs.cache_dir)
    assert len(after) == len(before) + 1, f"{label}: stage-1 key did not rotate"
    assert stubs.generate_calls == 2, f"{label}: the warm pointer was reused"


# ─── W05: a stage-1 pointer is validated, never trusted blindly ─────────────

def test_stale_pointer_is_rejected_not_returned(stubs, monkeypatch):
    """Simulate a pointer recorded by ANOTHER toolchain: same stage-1 key on
    disk (as an older key schema would have produced), but the entry's
    build_inputs.json disagrees with the current identity."""
    key, so, _ = _warm(stubs)
    rec = json.loads((so.parent / _cache.BUILD_INPUTS_FILE).read_text())
    rec["nvcc"] = "/old/nvcc:11.0"
    (so.parent / _cache.BUILD_INPUTS_FILE).write_text(json.dumps(rec))
    _warm(stubs)
    assert stubs.generate_calls == 2, "stale pointer handed back the old .so"
    # The regenerated bytes are identical -> content key re-hits the entry,
    # no nvcc, and the sidecar is left as the entry's own record.
    assert stubs.compile_calls == 1


class _HandleStub:
    def __init__(self, name, so_path, entry):
        self.name, self.so_path, self.entry = name, so_path, entry

    def apply_profile_overlay(self, *_):
        pass


def _get(stubs, monkeypatch, name="probe"):
    monkeypatch.setattr(grim, "RobotHandle", _HandleStub)
    monkeypatch.setattr(grim, "detect_cuda_arch", lambda: ARCH)
    h = grim.get_robot(name, cache_dir=stubs.cache_dir)
    return h


def test_get_robot_loads_a_registered_entry_and_refuses_an_incompatible_one(stubs, monkeypatch):
    """get_robot validates the LOAD subset of the identity (2026-09-24): a
    provenance change (nvcc) still loads; a wrapper/ABI/arch change or a
    missing sidecar raises StaleRobotError with the reasons, never an
    undefined-symbol crash from a stale .so."""
    key, so, _ = _warm(stubs)
    assert _get(stubs, monkeypatch).so_path == str(so)
    sidecar = so.parent / _cache.BUILD_INPUTS_FILE
    rec = json.loads(sidecar.read_text())
    sidecar.write_text(json.dumps(dict(rec, nvcc="/old/nvcc:11.0")))
    assert _get(stubs, monkeypatch).so_path == str(so), "provenance is not a load blocker"
    sidecar.write_text(json.dumps(dict(rec, wrapper_template="deadbeef")))
    with pytest.raises(grim.StaleRobotError) as ei:
        _get(stubs, monkeypatch)
    assert ei.value.reasons == [f"wrapper_template: recorded 'deadbeef' != current {rec['wrapper_template']!r}"]
    assert "register_robot" in str(ei.value)
    sidecar.unlink()
    with pytest.raises(grim.StaleRobotError, match="predates"):
        _get(stubs, monkeypatch)
    assert stubs.generate_calls == 1, "get_robot never builds"


def test_pointer_without_sidecar_is_a_miss(stubs):
    key, so, _ = _warm(stubs)
    (so.parent / _cache.BUILD_INPUTS_FILE).unlink()
    _warm(stubs)
    assert stubs.generate_calls == 2
    assert (so.parent / _cache.BUILD_INPUTS_FILE).exists(), "sidecar back-filled"


def test_incomplete_entry_rebuilds(stubs):
    key, so, _ = _warm(stubs)
    so.unlink()
    _warm(stubs)
    assert (stubs.generate_calls, stubs.compile_calls) == (2, 2)


def test_stale_reasons_are_readable(tmp_path):
    ident = _cache.build_identity(ARCH)
    entry = tmp_path / "entry"; entry.mkdir()
    assert _cache.stale_hit_reasons(entry, ident) == [
        "no build_inputs.json (entry predates the build-identity record)"]
    _cache.write_build_inputs(entry, ident)
    assert _cache.stale_hit_reasons(entry, ident) == []
    other = dict(ident, glass_content="x" * 64, glass_commit="label-only")
    reasons = _cache.stale_hit_reasons(entry, other)
    assert len(reasons) == 1 and reasons[0].startswith("glass_content:")


# ─── option isolation + cross-process stability ─────────────────────────────

def test_material_options_rotate_key(stubs):
    base = {"floating_base": False, "max_batch": 256, "ee_joint_names": []}
    k0 = _cache.compute_cache_key(URDF.encode(), base, ARCH)
    for change in ({"max_batch": 64}, {"dtype": "float64"}, {"floating_base": True},
                   {"contact_frames": ["foot"]}, {"algorithm_list": ["crba"]},
                   {"enable_mujoco_kernels": False}):
        assert _cache.compute_cache_key(URDF.encode(), {**base, **change}, ARCH) != k0, change
    assert _cache.compute_cache_key(URDF.encode(), base, ARCH + 1) != k0
    assert _cache.compute_cache_key(URDF.encode() + b" ", base, ARCH) != k0


def test_key_is_stable_across_processes():
    code = ("import json,sys; from grim import _cache as c; "
            "print(c.compute_cache_key(b'<robot/>', {'floating_base': False, "
            "'max_batch': 256, 'ee_joint_names': []}, 120))")
    env = {k: v for k, v in os.environ.items() if k not in _cache.GENERATION_ENV_KNOBS}
    outs = {subprocess.check_output([sys.executable, "-c", code], text=True,
                                    env=env).strip() for _ in range(2)}
    assert len(outs) == 1 and len(next(iter(outs))) == 64


# ─── W06: concurrent manifest registrations never lose a binding ────────────

def test_manifest_register_is_lost_update_safe(tmp_path):
    cache_dir = tmp_path / "cache"
    names = [f"robot_{i}" for i in range(24)]
    barrier = threading.Barrier(len(names))

    def reg(n):
        barrier.wait()
        _cache.manifest_register(cache_dir, n, "k" * 64, {"NUM_JOINTS": 1})

    threads = [threading.Thread(target=reg, args=(n,)) for n in names]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    registered = {e["name"] for e in _cache.list_registered(cache_dir)}
    assert registered == set(names)


# ─── abandoned staging dirs from killed builds are swept ─────────────────────

def test_dead_staging_dirs_are_swept_live_ones_kept(stubs):
    store = stubs.cache_dir / "store"
    store.mkdir(parents=True)
    dead = store / ".gen_999999999_deadbeef"; dead.mkdir()
    (dead / "grim.cuh").write_text("// orphan\n")
    live = store / f".gen_{os.getpid()}_cafebabe"; live.mkdir()
    _warm(stubs)
    assert not dead.exists(), "orphaned staging dir from a dead pid survived"
    assert live.exists(), "a live builder's staging dir was removed"


# ─── W10: build_plan resolves everything and touches nothing ────────────────

def test_build_plan_is_read_only_and_tracks_the_cache(stubs):
    plan = grim.build_plan("probe", urdf_string=URDF, cache_dir=stubs.cache_dir, cuda_arch=ARCH)
    assert plan["cached"] is False and plan["content_key"] is None and plan["would"].startswith("generate")
    assert plan["build_identity"]["cuda_arch"] == ARCH and len(plan["input_key"]) == 64
    assert (stubs.generate_calls, stubs.compile_calls) == (0, 0), "a plan must not build"
    assert not (stubs.cache_dir / "bykey").exists(), "a plan must not record a pointer"
    key, so, _ = _warm(stubs)
    plan = grim.build_plan("probe", urdf_string=URDF, cache_dir=stubs.cache_dir, cuda_arch=ARCH)
    assert plan["cached"] is True and plan["content_key"] == key and plan["would"] == "load"
    assert plan["input_key"] == _bykey_entries(stubs.cache_dir)[0]
    # a stale pointer is reported with its reasons, not silently reused
    rec = json.loads((so.parent / _cache.BUILD_INPUTS_FILE).read_text()); rec["nvcc"] = "/old/nvcc:11.0"
    (so.parent / _cache.BUILD_INPUTS_FILE).write_text(json.dumps(rec))
    plan = grim.build_plan("probe", urdf_string=URDF, cache_dir=stubs.cache_dir, cuda_arch=ARCH)
    assert plan["cached"] is False and plan["stale_reasons"] and plan["stale_reasons"][0].startswith("nvcc:")
    assert (stubs.generate_calls, stubs.compile_calls) == (1, 1)


def test_precompile_numpy_builds_without_a_handle(stubs, monkeypatch):
    def _no_handle(*a, **k):
        raise AssertionError("precompile(backends=['numpy']) must not construct a RobotHandle")
    monkeypatch.setattr(grim, "RobotHandle", _no_handle)
    out = grim.precompile("probe", urdf_string=URDF, cache_dir=stubs.cache_dir, cuda_arch=ARCH,
                              backends=["numpy"])
    assert (stubs.generate_calls, stubs.compile_calls) == (1, 1)
    assert out and out[0]["name"] == "probe" and out[0]["backend"] == "numpy" and "cache_key" in out[0]


# ─── R2: an in-process GLASS/toolchain change is noticed on the next query ───

def test_glass_edit_in_the_same_process_changes_the_identity(tmp_path, monkeypatch):
    root = tmp_path / "GLASS"; (root / "src" / "base").mkdir(parents=True)
    hdr = root / "src" / "base" / "gemm.cuh"; hdr.write_text("// v1\n")
    (root / "glass.cuh").write_text("#include \"src/base/gemm.cuh\"\n")
    monkeypatch.setattr(_cache, "_glass_root", lambda: root)
    _cache.refresh_build_identity()
    h1 = _cache._glass_content_hash()
    assert h1 == _cache._glass_content_hash(), "memo must hold while nothing changed"
    hdr.write_text("// v2 — a REAL edit after the first query\n")
    h2 = _cache._glass_content_hash()
    assert h2 != h1, "an in-process GLASS edit was not noticed"
    k1 = _cache.compute_cache_key(b"<robot/>", {"floating_base": False, "max_batch": 256, "ee_joint_names": []}, ARCH)
    hdr.write_text("// v3\n")
    k2 = _cache.compute_cache_key(b"<robot/>", {"floating_base": False, "max_batch": 256, "ee_joint_names": []}, ARCH)
    assert k1 != k2, "the stage-1 key did not follow the in-process edit"
    # explicit escape hatch for what metadata cannot see
    _cache.refresh_build_identity()
    assert _cache._glass_content_hash() == _cache._glass_content_hash()


def test_toolchain_path_change_in_the_same_process_refreshes_the_tags(tmp_path, monkeypatch):
    fake = tmp_path / "bin"; fake.mkdir()
    nv = fake / "nvcc"; nv.write_text("#!/bin/sh\necho 'fake nvcc 1.0'\n"); nv.chmod(0o755)
    monkeypatch.setenv("PATH", f"{fake}:{os.environ['PATH']}")
    _cache.refresh_build_identity()
    t1 = _cache._nvcc_identity()
    assert "fake nvcc 1.0" in t1
    nv.write_text("#!/bin/sh\necho 'fake nvcc 2.0 with a longer banner'\n")  # size + mtime change
    t2 = _cache._nvcc_identity()
    assert "fake nvcc 2.0" in t2 and t2 != t1, "a replaced compiler binary was not noticed"
    _cache.refresh_build_identity()


# ─── R3: build_plan leaves an absent cache root absent ──────────────────────

def test_build_plan_does_not_create_the_cache_root(stubs, tmp_path):
    root = tmp_path / "never_created"
    assert not root.exists()
    plan = grim.build_plan("probe", urdf_string=URDF, cache_dir=root, cuda_arch=ARCH)
    assert plan["cached"] is False and not root.exists(), "build_plan created the cache root"
    _warm(stubs)  # a build still creates its own root
    assert stubs.cache_dir.exists()
